### ISSUE TITLE
Ensure err is an Error when handling the err from running a task

### ISSUE THREAD

**Issue by paulscheltema** [senecajs/gate-executor#10]
at line: 
https://github.com/senecajs/gate-executor/blob/master/gate-executor.js#L149

When the error of the error case you handle there is not actually an instance of Error, you will get a stacktrace from inside gate-executioner and no reference as to where the error originated inside your own code.

adding
```
            if (!(err instanceof Error)) {
              err = new Error(err);
            }
```

will fix it.

**Comment by mcdonnelldean** [comment]
Moved to https://github.com/senecajs/seneca/issues/500
