### ISSUE TITLE
timeout bug

### ISSUE THREAD

**Issue by paolochiodi** [senecajs/gate-executor#16]
When gate-executor switched from jobs-specific setTimeouts to a generic setInterval a new bug has been introduced.

When the queue is empty the setInterval is cleared, but when a new job is added to the queue it isn't restarted.
This means that jobs added after the first "clear" will never fire a timeout.

Here's a PR with a test that exposes the bug: https://github.com/senecajs/gate-executor/pull/15

This is the cause of the error reported in:
https://github.com/senecajs/seneca-amqp-transport/issues/48 
https://github.com/senecajs/seneca/issues/517

**Comment by paolochiodi** [comment]
Another possible bug is that work.callback() is called before work.ontm() in https://github.com/senecajs/gate-executor/blob/master/gate-executor.js#L210. 

I think it's preferable to have the timeout handler called before the callback.

**Comment by nfantone** [comment]
This was closed by #15 .
