### ISSUE TITLE
Consider using fastparallel instead of setImmediate?

### ISSUE THREAD

**Issue by AdrianRossouw** [senecajs/gate-executor#3]
I was doing some tracing of an application, and I noted that there was a non-trivial amounts of calls to setImmediate being made in a misbehaving seneca application. It might be a simple but practical micro-optimization.

Also i recall needing to use a setImmediate library to deal with some strange browser compatibility issue in the past, so this might be good for cross-platform support.

https://github.com/mcollina/fastparallel

**Comment by mcdonnelldean** [comment]
@mcollina Your thoughts on this? Since the gate-executor would be, by definition, pretty hot.

**Comment by mcollina** [comment]
Sure, there are plenty of perf optimizations that are doable here. I'll do a pass.

**Comment by rjrodger** [comment]
does match the desired execution model (i.e gating)
